version: "3"
services:
  nginx:
    image: nginx:1.16.0
    tty: true
    volumes:
      - ../assets/public:/var/www/html
      - ../logs/nginx:/var/log/nginx
      - ./nginx/conf:/etc/nginx/conf.d
    ports:
      - 8080:80
  node:
    image: node:12.4.0
    tty: true
    volumes:
      - ../assets:/var/www/html
      - ./node/bin:/var/bin
      - ./node/conf:/etc/profile.d
    ports:
      - 8081:8080
    command: "sh /var/bin/start.sh"
  golang:
    image: golang:1.12.6
    tty: true
    volumes:
      - ../app:/var/www/html
    ports:
      - 80:80
